openapi: 3.0.4
info:
  title: Baby Name Generator
  description: >-
    Baby Name Generator is a simple tool for generating baby names. It returns a
    list of baby names.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/babynamegenerator:
    get:
      summary: Generate Baby Names
      description: Generate a baby's first and middle name, based on the provided gender
      operationId: babynamegenerator
      parameters:
        - name: gender
          in: query
          schema:
            type: string
          required: true
          description: The gender for the generated names
          example: male
        - name: count
          in: query
          schema:
            type: integer
          required: false
          description: The number of names to generate
          example: 1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  count: 1
                  names:
                    - firstName: Myra
                      middleName: Sherri
                      fullName: Myra Sherri
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
