openapi: 3.0.4
info:
  title: Baby Name Generator
  description: Baby Name Generator is a simple tool for generating baby names. It returns a list of baby names.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/babynamegenerator:
    get:
      summary: Generate Baby Names
      description: Baby Name Generator is a simple tool for generating baby names. It returns a list of baby names.
      operationId: babynamegenerator
      parameters:
      - name: gender
        in: query
        schema:
          type: string
        required: true
        description: The gender you would like the generated names to be based off (e.g. male, female)
        example: male
      - name: count
        default: '1'
        in: query
        schema:
          type: integer
        required: false
        description: The number of names to generate
        example: '1'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  count: 3
                  names:
                  - firstName: Gladys
                    middleName: Emily
                    fullName: Gladys Emily
                  - firstName: Sandra
                    middleName: Tasha
                    fullName: Sandra Tasha
                  - firstName: Patricia
                    middleName: Rosemary
                    fullName: Patricia Rosemary
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
